config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root :to => 'sessions#new'

  resources :plants 
  resources :plots do
    member do
     put :plant
     put :harvest
     put :buyPlot
     put :buyPlant
     put :exitPlantShop
     put :water
     put :refreshAttributes
    end
  end
  resources :users
  
  put '/buyPlot' => 'plots#buyPlot'
  put '/buyPlant' => 'plots#buyPlant'
  
  
  get '/show' => 'plants#show'
  

  
  get       '/signup',  to: 'users#new'
  get       '/login',   to: 'sessions#new'
  post      '/signup',  to: 'sessions#create'
  post      '/login',   to: 'sessions#create'
  resources :users
  
end

app/models/plant.rb
# The Plant model is responsible for acting as a blueprint to all plant types.
class Plant < ActiveRecord::Base

    # Plant attribute validation.
    validates_presence_of :name, :minWater, :maxWater, 
        :secondsWaterTakesToDecreaseOneLevel, :harvestGold, :harvestTime,
        :description, :cost

end

app/controllers/plants_controller.rb
# The User controller is responsible for all plant-related methods.
class PlantsController < ApplicationController

  def plant_params
    params.require(:plant).permit(:name, :waterLevel, :description, :cost)
  end

  def id
    id = params[:id] # retrieve ID from URI route
    @plant = Plant.find(id) # look up by unique ID
  end
  
  def index
        
        # will render app/views/plots/index.<extension> by default
  end

  def show
    @plants = Plant.all
    # will render app/views/plants/show.<extension> by default
  end

  def new
    # default: render 'new' template
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/views/plants/index.html.erb
<% # in app/views/plants/index.html.erb %>

<%= button_to 'Plant Database', plants_path + '/show', :method => "get" %>

app/views/plants/show.html.erb
<% # in app/views/plants/show.html.erb %>
<h1>All Plants</h1>
<table id="plants">
  <thead>
    <tr>
      <th>Name</th>
      <th>Min Water Level</th>
      <th>Max Water Level</th>
      <th>Water Level Decrease Time(s)[N/A]</th>
      <th>Harvest Time(s)</th>
      <th>Harvest Amount (Gold)</th>
      <th>Description</th>
      <th>Cost (Gold)</th>
    </tr>
  </thead>
  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td>
          <%= plant.name  %>
        </td>
        <td style="text-align: center; vertical-align: middle;">
          <%= plant.minWater %>
        </td>
        <td style="text-align: center; vertical-align: middle;">
          <%= plant.maxWater %>
        </td>
        <td style="text-align: center; vertical-align: middle;">
          <%= plant.secondsWaterTakesToDecreaseOneLevel %>
        </td>
        <td style="text-align: center; vertical-align: middle;">
          <%= plant.harvestTime %>
        </td>
        <td style="text-align: center; vertical-align: middle;">
          <%= plant.harvestGold %>
        </td>
        <td>
          <%= plant.description %>
        </td>
        <td style="text-align: center; vertical-align: middle;">
          <%= plant.cost %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', plots_path %>